server:
  port: 8080

spring:
  application:
    name: auth-service

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 2000
      max-lifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

  logging:
    level:
      liquibase: DEBUG
      org.springframework.boot.autoconfigure.liquibase: DEBUG


redis:
  host: redis
  port: 6379
  password:
  timeout-ms: 2000
  max-total: 20
  max-idle: 10
  min-idle: 2


app:
  kafka:
    topics:
      otp-requested: auth.otp.requested
      user-registered: auth.user.registered

  outbox:
    worker:
      enabled: true
      fixed-delay-ms: 3000
      batch-size: 50
      max-attempts: 5

  jwt:
    issuer: tripify-auth
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 30
    secret: da422807dea6119e0752c14b58235a2e3f76dd88bbeac6be3ce9303481df04bc

springdoc:
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
  swagger-ui:
    path: /v3/swagger-ui.html
    disable-swagger-default-url: true
    try-it-out-enabled: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha