server:
  port: 8080

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

tripify:
  kafka:
    topics:
      otp-requested: auth.otp.requested

  notification:
    providers:
      aero-sms:
        enabled: true
        name: AeroSms
        email: semaclasss@mail.ru
        api-key: UkiOdPKZRgJDyRansau-SyCXEzSfRxS3
        sign: SMS Aero