openapi: 3.0.3

info:
  title: Tripify User Service API
  description: API contracts for user service
  version: 1.0.0

servers:
  - url: http://localhost:8083
    description: Local environment
  - url: https://tripify.com
    description: Production environment

tags:
  - name: USER_INFO

security:
  - bearerAuth: []

paths:
  /users/profile:
    $ref: './paths/users-profile.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      $ref: './components/responses.yaml#/Unauthorized'
    InternalServerError:
      $ref: './components/responses.yaml#/InternalServerError'
    NotFound:
      $ref: './components/responses.yaml#/NotFound'
    BadRequest:
      $ref: './components/responses.yaml#/BadRequest'


  schemas:
    UserProfileResponse:
      $ref: './components/schemas/UserProfileResponse.yaml'
    UpdateUserProfileRequest:
      $ref: './components/schemas/UpdateUserProfileRequest.yaml'