openapi: 3.0.3

info:
  title: Auth Service API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: OTP
  - name: Tokens

paths:
  /auth/otp/request:
    $ref: './paths/otp.yaml#/requestOtp'

  /auth/otp/verify:
    $ref: './paths/otp.yaml#/verifyOtp'

  /auth/refresh:
    $ref: './paths/tokens.yaml#/refreshToken'

  /auth/logout:
    $ref: './paths/tokens.yaml#/logout'

components:
  securitySchemes:
    cookieAuth:
      $ref: './components/security-schemes.yaml#/cookieAuth'

  responses:
    BadRequest:
      $ref: './components/responses.yaml#/BadRequest'
    Unauthorized:
      $ref: './components/responses.yaml#/Unauthorized'
    TooManyRequests:
      $ref: './components/responses.yaml#/TooManyRequests'

  schemas:
    OtpRequest:
      $ref: './components/schemas/otp.yaml#/OtpRequest'
    OtpVerifyRequest:
      $ref: './components/schemas/otp.yaml#/OtpVerifyRequest'

    ErrorResponse:
      $ref: './components/schemas/errors.yaml#/ErrorResponse'
    ErrorDetail:
      $ref: './components/schemas/errors.yaml#/ErrorDetail'
