openapi: 3.0.3

info:
  title: Tripify Hotels Service API
  description: API contracts for hotels service
  version: 1.0.0

servers:
  - url: http://localhost:8084
    description: Local environment
  - url: https://tripify.com
    description: Production environment

tags:
  - name: hotels
    description: Hotels search and details API

paths:
  /hotels:
    $ref: './paths/hotels.yaml'

  /hotels/search:
    $ref: './paths/hotel-search.yaml'

  /hotels/filters:
    $ref: './paths/hotel-filters.yaml'

  /hotels/{hotelId}:
    $ref: './paths/hotel-by-id.yaml'