package com.tripify.info.exception;

public enum InfoErrorCode {
    COUNTRY_INFO_NOT_FOUND,
    COUNTRY_CONFIG_NOT_FOUND,
    COUNTRY_INFO_REFRESH_FAILED,
    TUTU_PAGE_DOWNLOAD_FAILED,
    TUTU_PAGE_PARSE_FAILED,
    INVALID_COUNTRY_CODE,
    INVALID_CURRENCY_CODE,
    INVALID_STAY_DATES,
    WEATHER_FORECAST_FAILED,
    INTERNAL_ERROR
}
